//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellaLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StellaLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_gameplay {
            get {
                object obj = ResourceManager.GetObject("bg_gameplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_links {
            get {
                object obj = ResourceManager.GetObject("bg_links", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_main {
            get {
                object obj = ResourceManager.GetObject("bg_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_support_me {
            get {
                object obj = ResourceManager.GetObject("bg_support-me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_tools {
            get {
                object obj = ResourceManager.GetObject("bg_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat {
            get {
                object obj = ResourceManager.GetObject("cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliWrap: {0} installed. Exit code: {1}
        ///
        ///The requested operation is successful. Changes will not be effective until the system is rebooted..
        /// </summary>
        internal static string Cmd__AppInstalled {
            get {
                return ResourceManager.GetString("Cmd__AppInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliWrap: Command execution failed. An update is required..
        /// </summary>
        internal static string Cmd_CommandExecutionFailed {
            get {
                return ResourceManager.GetString("Cmd_CommandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution failed because the underlying process ({0}) returned a non-zero exit code - {1}.
        ///
        ///{2}.
        /// </summary>
        internal static string Cmd_CommandExecutionFailedBeacuseTheUnderlyingProcessReturnedANonZeroExitCode {
            get {
                return ResourceManager.GetString("Cmd_CommandExecutionFailedBeacuseTheUnderlyingProcessReturnedANonZeroExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Cmd_Error {
            get {
                return ResourceManager.GetString("Cmd_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed command.
        /// </summary>
        internal static string Cmd_ExecutedCommand {
            get {
                return ResourceManager.GetString("Cmd_ExecutedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        internal static string Cmd_ExitCode {
            get {
                return ResourceManager.GetString("Cmd_ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update. The software was denied access to a location, preventing it from saving, copying, opening or loading files..
        /// </summary>
        internal static string Cmd_FailedToUpdate {
            get {
                return ResourceManager.GetString("Cmd_FailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot is required.
        /// </summary>
        internal static string Cmd_RebootIsRequired {
            get {
                return ResourceManager.GetString("Cmd_RebootIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart your computer or suspend antivirus program and try again..
        /// </summary>
        internal static string Cmd_RestartYourComputerOrSuspendAntivirusProgramAndTryAgain {
            get {
                return ResourceManager.GetString("Cmd_RestartYourComputerOrSuspendAntivirusProgramAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliWrap: Successfully executed {0}; Exit code: {1}; Start time: {2}; Exit time: {3}{4}{5};.
        /// </summary>
        internal static string Cmd_SuccessfullyExecutedCommand {
            get {
                return ResourceManager.GetString("Cmd_SuccessfullyExecutedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation was successful, but your computer needs to be restarted..
        /// </summary>
        internal static string Cmd_TheRequestOperationWasSuccessfulButYourPCNeedsToBeRebooted {
            get {
                return ResourceManager.GetString("Cmd_TheRequestOperationWasSuccessfulButYourPCNeedsToBeRebooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required dependency has been successfully installed, but your computer needs to be restarted..
        /// </summary>
        internal static string Cmd_TheRequiredDependencyHasBeenSuccessfullyInstalledButyourComputerNeedsToBeRestart {
            get {
                return ResourceManager.GetString("Cmd_TheRequiredDependencyHasBeenSuccessfullyInstalledButyourComputerNeedsToBeRest" +
                        "art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is required.
        ///
        ///We apologize for any inconvenience caused, but it is necessary to install every new update. These updates may contain quality improvements, and some may even include important security fixes.
        ///
        ///If, for any reason, you are unable to update Stella Mod through the Launcher, please uninstall the current version and install the new one from the official website source..
        /// </summary>
        internal static string Cmd_UpdateIsRequired {
            get {
                return ResourceManager.GetString("Cmd_UpdateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        internal static string Cmd_WorkingDirectory {
            get {
                return ResourceManager.GetString("Cmd_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update ReShade configuration?
        ///
        ///This action will result in the loss of any custom configurations you have made. If you do not have any custom configurations, you may proceed by clicking Yes. However, if you have made changes, please ensure that you have backed up the previous ReShade file in your game files..
        /// </summary>
        internal static string Default_AreYouSureWantToUpdateReShadeConfiguration {
            get {
                return ResourceManager.GetString("Default_AreYouSureWantToUpdateReShadeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background file was not found in &apos;{0}&apos;; ID: {1};.
        /// </summary>
        internal static string Default_BackgroundFileWasNotFoundIn__ID {
            get {
                return ResourceManager.GetString("Default_BackgroundFileWasNotFoundIn_.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached app background in RAM memory &apos;{0}&apos;; ID: {1};.
        /// </summary>
        internal static string Default_CachedAppBackground_ID {
            get {
                return ResourceManager.GetString("Default_CachedAppBackground_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by the user. Are you sure of what you&apos;re doing?.
        /// </summary>
        internal static string Default_CanceledByTheUser_AreYouSureOfWhatYoureDoing {
            get {
                return ResourceManager.GetString("Default_CanceledByTheUser_AreYouSureOfWhatYoureDoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed the launcher background. ID: {0}.
        /// </summary>
        internal static string Default_ChangedTheLauncherBackground_ID {
            get {
                return ResourceManager.GetString("Default_ChangedTheLauncherBackground_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Default_CheckForUpdates {
            get {
                return ResourceManager.GetString("Default_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string Default_CheckingForUpdates {
            get {
                return ResourceManager.GetString("Default_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click „Start game” button to inject ReShade and use FPS Unlock..
        /// </summary>
        internal static string Default_ClickStartGameButtonToInjectReShadeAndUseFPSUnlock {
            get {
                return ResourceManager.GetString("Default_ClickStartGameButtonToInjectReShadeAndUseFPSUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current background: {0}.
        /// </summary>
        internal static string Default_CurrentBackground {
            get {
                return ResourceManager.GetString("Default_CurrentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current background: Default.
        /// </summary>
        internal static string Default_CurrentBackground_Default {
            get {
                return ResourceManager.GetString("Default_CurrentBackground_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted old setup file from temp directory..
        /// </summary>
        internal static string Default_DeletedOldSetupFromTempDirectory {
            get {
                return ResourceManager.GetString("Default_DeletedOldSetupFromTempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted old setup file from temp folder: {0}.
        /// </summary>
        internal static string Default_DeletedOldSetupFromTempFolder {
            get {
                return ResourceManager.GetString("Default_DeletedOldSetupFromTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [x] Directory {0} was not found..
        /// </summary>
        internal static string Default_Directory_WasNotFound {
            get {
                return ResourceManager.GetString("Default_Directory_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Default_Done {
            get {
                return ResourceManager.GetString("Default_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded ReShade.ini was not found in: {0}.
        /// </summary>
        internal static string Default_DownloadedReShadeIniWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Default_DownloadedReShadeIniWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Default_Downloading {
            get {
                return ResourceManager.GetString("Default_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading config file for FPS Unlocker....
        /// </summary>
        internal static string Default_DownloadingConfigFileForFPSUnlocker {
            get {
                return ResourceManager.GetString("Default_DownloadingConfigFileForFPSUnlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download....
        /// </summary>
        internal static string Default_FailedToDownload {
            get {
                return ResourceManager.GetString("Default_FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download unlocker.config.json..
        /// </summary>
        internal static string Default_FailedToDownloadUnlockerConfigJson {
            get {
                return ResourceManager.GetString("Default_FailedToDownloadUnlockerConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found..
        /// </summary>
        internal static string Default_File_WasNotFound {
            get {
                return ResourceManager.GetString("Default_File_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File download has been canceled by the user..
        /// </summary>
        internal static string Default_FileDownloadHasBeenCanceledByTheUser {
            get {
                return ResourceManager.GetString("Default_FileDownloadHasBeenCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found..
        /// </summary>
        internal static string Default_FileWasNotFound {
            get {
                return ResourceManager.GetString("Default_FileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, you did not give consent for the automatic update of the ReShade file. Please note that older versions of this file may not be compatible with newer versions of Stella Mod. I hope you know what you&apos;re doing..
        /// </summary>
        internal static string Default_ForSomeReasonYouDidNotGiveConsentForTheAutomaticUpdateOfTheReShadeFile {
            get {
                return ResourceManager.GetString("Default_ForSomeReasonYouDidNotGiveConsentForTheAutomaticUpdateOfTheReShadeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game launcher was not found..
        /// </summary>
        internal static string Default_GameLauncherWasNotFound {
            get {
                return ResourceManager.GetString("Default_GameLauncherWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game launcher was not found in: {0}.
        /// </summary>
        internal static string Default_GameLauncherWasNotFoundIn {
            get {
                return ResourceManager.GetString("Default_GameLauncherWasNotFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you are launching the launcher for the first time! Take a moment to review the terms of use on the GitHub Wiki and other guidelines for this modification to avoid any unexpected issues.
        ///
        ///REMEMBER NOT TO SHARE YOUR UID WITH VISIBLE GAME SHADERS WITH ANYONE!.
        /// </summary>
        internal static string Default_ItAppersThatIsYourFirstTimeLaunchingTheLauncher {
            get {
                return ResourceManager.GetString("Default_ItAppersThatIsYourFirstTimeLaunchingTheLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just text. What more do you want?.
        /// </summary>
        internal static string Default_ItsJustText_WhatMoreDoYouWant {
            get {
                return ResourceManager.GetString("Default_ItsJustText_WhatMoreDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeow! Failed to download ReShade.ini. Try again..
        /// </summary>
        internal static string Default_Meeow_FailedToDownloadReShadeIni_TryAgain {
            get {
                return ResourceManager.GetString("Default_Meeow_FailedToDownloadReShadeIni_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any new updates. Your installed version: v{0}.
        /// </summary>
        internal static string Default_NotFoundAnyNewUpdates_YourInstalledVersion_ {
            get {
                return ResourceManager.GetString("Default_NotFoundAnyNewUpdates_YourInstalledVersion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh, something went wrong.
        /// </summary>
        internal static string Default_OhhSomethingWentWrong {
            get {
                return ResourceManager.GetString("Default_OhhSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing sound file: {0}.
        /// </summary>
        internal static string Default_PlayingSoundFile_ {
            get {
                return ResourceManager.GetString("Default_PlayingSoundFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while checking for new updates.
        ///
        ///{0}.
        /// </summary>
        internal static string Default_SomethingWentWrongWhileCheckingForNewUpdates {
            get {
                return ResourceManager.GetString("Default_SomethingWentWrongWhileCheckingForNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Background {0} was not found..
        /// </summary>
        internal static string Default_Sorry_Background_WasNotFound {
            get {
                return ResourceManager.GetString("Default_Sorry.Background_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Default_Success {
            get {
                return ResourceManager.GetString("Default_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded ReShade.ini!.
        /// </summary>
        internal static string Default_SuccessfullyDownloadedReShadeIni {
            get {
                return ResourceManager.GetString("Default_SuccessfullyDownloadedReShadeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded ReShade.ini and saved in: {0}.
        /// </summary>
        internal static string Default_SuccessfullyDownloadedReShadeIniAndSavedIn {
            get {
                return ResourceManager.GetString("Default_SuccessfullyDownloadedReShadeIniAndSavedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved and updated the cached app background with ID {0}..
        /// </summary>
        internal static string Default_SuccessfullyRetrievedAndUpdatedTheCachedAppBackgroundWithID_ {
            get {
                return ResourceManager.GetString("Default_SuccessfullyRetrievedAndUpdatedTheCachedAppBackgroundWithID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application background has been changed to default. ID: {0}.
        /// </summary>
        internal static string Default_TheApplicationBackgroundHasBeenChangedToDefault_ID {
            get {
                return ResourceManager.GetString("Default_TheApplicationBackgroundHasBeenChangedToDefault_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReShade.ini file could not be located in your game files, or it may not be compatible with the current version.
        ///
        ///Would you like to download this file now to prevent future errors and manual configuration? Recommended..
        /// </summary>
        internal static string Default_TheReShadeIniFileCouldNotBeLocatedInYourGameFiles {
            get {
                return ResourceManager.GetString("Default_TheReShadeIniFileCouldNotBeLocatedInYourGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReShade.ini file still does not exist!.
        /// </summary>
        internal static string Default_TheReShadeIniFileStillDoesNotExist {
            get {
                return ResourceManager.GetString("Default_TheReShadeIniFileStillDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound file with music was not found..
        /// </summary>
        internal static string Default_TheSoundFileWithMusicWasNotFound {
            get {
                return ResourceManager.GetString("Default_TheSoundFileWithMusicWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound file with music was not found in the location: &apos;{0}&apos;.
        /// </summary>
        internal static string Default_TheSoundFileWithMusicWasNotFoundInTheLocalization_ {
            get {
                return ResourceManager.GetString("Default_TheSoundFileWithMusicWasNotFoundInTheLocalization_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of ReShade.ini has been cancelled by the user..
        /// </summary>
        internal static string Default_TheUpdateOfReShadIniHasBeenCanceledByTheUser {
            get {
                return ResourceManager.GetString("Default_TheUpdateOfReShadIniHasBeenCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string Default_YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("Default_YouHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best mod for Genshin Impact with ReShade, custom graphics presets, FPS unlock, custom launcher, and more!.
        /// </summary>
        internal static string Discord_Desc {
            get {
                return ResourceManager.GetString("Discord_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord server.
        /// </summary>
        internal static string Discord_DiscordServer {
            get {
                return ResourceManager.GetString("Discord_DiscordServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the main window.
        /// </summary>
        internal static string Discord_InTheMainWindow {
            get {
                return ResourceManager.GetString("Discord_InTheMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official website.
        /// </summary>
        internal static string Discord_OfficialWebsite {
            get {
                return ResourceManager.GetString("Discord_OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: Closed..
        /// </summary>
        internal static string Discord_OnClose {
            get {
                return ResourceManager.GetString("Discord_OnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: Connection successfully..
        /// </summary>
        internal static string Discord_OnConnectionEstablished {
            get {
                return ResourceManager.GetString("Discord_OnConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: An error occurred during the transmission of a message..
        /// </summary>
        internal static string Discord_OnError {
            get {
                return ResourceManager.GetString("Discord_OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: Presence has been updated..
        /// </summary>
        internal static string Discord_OnPresenceUpdate {
            get {
                return ResourceManager.GetString("Discord_OnPresenceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: Connected to Discord with user {0}..
        /// </summary>
        internal static string Discord_OnReady {
            get {
                return ResourceManager.GetString("Discord_OnReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC: Unsubscribed..
        /// </summary>
        internal static string Discord_OnUnsubscribe {
            get {
                return ResourceManager.GetString("Discord_OnUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Rich Presence was not updated. Data: {0}; IsReady: {1}.
        /// </summary>
        internal static string Discord_RPCWasNotUpdated {
            get {
                return ResourceManager.GetString("Discord_RPCWasNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Discord_Version_ {
            get {
                return ResourceManager.GetString("Discord_Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_controller {
            get {
                object obj = ResourceManager.GetObject("flaticon_controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_donation {
            get {
                object obj = ResourceManager.GetObject("flaticon_donation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_redo {
            get {
                object obj = ResourceManager.GetObject("flaticon_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_settings {
            get {
                object obj = ResourceManager.GetObject("flaticon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing the gallery 📷.
        /// </summary>
        internal static string Gallery_BrowsingTheGallery {
            get {
                return ResourceManager.GetString("Gallery_BrowsingTheGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited the gallery 🦊.
        /// </summary>
        internal static string Gallery_ExitedTheGallery {
            get {
                return ResourceManager.GetString("Gallery_ExitedTheGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching gameplay 🎮.
        /// </summary>
        internal static string Gameplay_WatchingGameplay {
            get {
                return ResourceManager.GetString("Gameplay_WatchingGameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_animated {
            get {
                object obj = ResourceManager.GetObject("icons8_animated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_available_updates {
            get {
                object obj = ResourceManager.GetObject("icons8_available-updates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_discord {
            get {
                object obj = ResourceManager.GetObject("icons8_discord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_download_from_the_cloud {
            get {
                object obj = ResourceManager.GetObject("icons8_download-from-the-cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_property {
            get {
                object obj = ResourceManager.GetObject("icons8_edit-property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_gear {
            get {
                object obj = ResourceManager.GetObject("icons8_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_github {
            get {
                object obj = ResourceManager.GetObject("icons8_github", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_info_squared {
            get {
                object obj = ResourceManager.GetObject("icons8_info-squared", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_notepad {
            get {
                object obj = ResourceManager.GetObject("icons8_notepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_recycle_bin {
            get {
                object obj = ResourceManager.GetObject("icons8_recycle-bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shortcut {
            get {
                object obj = ResourceManager.GetObject("icons8_shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_support {
            get {
                object obj = ResourceManager.GetObject("icons8_support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_tools {
            get {
                object obj = ResourceManager.GetObject("icons8_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_web {
            get {
                object obj = ResourceManager.GetObject("icons8_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_youtube {
            get {
                object obj = ResourceManager.GetObject("icons8_youtube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the window with links 🌍.
        /// </summary>
        internal static string Links_DRPC_OnTheWindowWithLinks {
            get {
                return ResourceManager.GetString("Links_DRPC_OnTheWindowWithLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, I cannot save the action information in the log file..
        /// </summary>
        internal static string Log_ForSomeReasonICannotSaveTheActionInfoInTheLogFile {
            get {
                return ResourceManager.GetString("Log_ForSomeReasonICannotSaveTheActionInfoInTheLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, I can&apos;t save the error information in the log file..
        /// </summary>
        internal static string Log_ForSomeReasonICantSaveTheErrorInfoInTheLogFile {
            get {
                return ResourceManager.GetString("Log_ForSomeReasonICantSaveTheErrorInfoInTheLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Log_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Log_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked No in form &apos;{0}&apos;..
        /// </summary>
        internal static string Main_ClickedNoInForm_ {
            get {
                return ResourceManager.GetString("Main_ClickedNoInForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked Yes in form &apos;{0}&apos;..
        /// </summary>
        internal static string Main_ClickedYesInForm_ {
            get {
                return ResourceManager.GetString("Main_ClickedYesInForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed..
        /// </summary>
        internal static string Main_Closed {
            get {
                return ResourceManager.GetString("Main_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed form {0}..
        /// </summary>
        internal static string Main_ClosedForm_ {
            get {
                return ResourceManager.GetString("Main_ClosedForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing form {0}....
        /// </summary>
        internal static string Main_ClosingForm_ {
            get {
                return ResourceManager.GetString("Main_ClosingForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded form {0}..
        /// </summary>
        internal static string Main_LoadedForm_ {
            get {
                return ResourceManager.GetString("Main_LoadedForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Main_PleaseWait {
            get {
                return ResourceManager.GetString("Main_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version is available.
        /// </summary>
        internal static string MajorRelease_MajorVersionIsAvailable {
            get {
                return ResourceManager.GetString("MajorRelease_MajorVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New major version from {0} is available: v{1} → v{2}.
        /// </summary>
        internal static string MajorRelease_NewMajorVersionFrom_IsAvailable_v_ {
            get {
                return ResourceManager.GetString("MajorRelease_NewMajorVersionFrom_IsAvailable_v_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_release {
            get {
                object obj = ResourceManager.GetObject("new-release", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to update.
        /// </summary>
        internal static string NormalRelease_ClickHereToUpdate {
            get {
                return ResourceManager.GetString("NormalRelease_ClickHereToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string NormalRelease_Closing {
            get {
                return ResourceManager.GetString("NormalRelease_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing launcher in {0}s....
        /// </summary>
        internal static string NormalRelease_ClosingLauncherIn_ {
            get {
                return ResourceManager.GetString("NormalRelease_ClosingLauncherIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted old setup file from temp directory..
        /// </summary>
        internal static string NormalRelease_DeletedOldSetupFileFromTempDir {
            get {
                return ResourceManager.GetString("NormalRelease_DeletedOldSetupFileFromTempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted od setup file from: {0}.
        /// </summary>
        internal static string NormalRelease_DeletedOldSetupFireFrom_ {
            get {
                return ResourceManager.GetString("NormalRelease_DeletedOldSetupFireFrom_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading in progress....
        /// </summary>
        internal static string NormalRelease_DownloadingInProgress {
            get {
                return ResourceManager.GetString("NormalRelease_DownloadingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new update... {0} MB of {1} MB / {2} MB/s.
        /// </summary>
        internal static string NormalRelease_DownloadingNewUpdate_ {
            get {
                return ResourceManager.GetString("NormalRelease_DownloadingNewUpdate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update... {0} MB / {1} MB.
        /// </summary>
        internal static string NormalRelease_DownloadingUpdate_ {
            get {
                return ResourceManager.GetString("NormalRelease_DownloadingUpdate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is okay! Starting setup....
        /// </summary>
        internal static string NormalRelease_EverythingIsOkay_StartingSetup {
            get {
                return ResourceManager.GetString("NormalRelease_EverythingIsOkay_StartingSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a new version in the wizard. Closing launcher in {0}s....
        /// </summary>
        internal static string NormalRelease_InstallANewVersionInTheWizard_ClosingLauncherIn_ {
            get {
                return ResourceManager.GetString("NormalRelease_InstallANewVersionInTheWizard_ClosingLauncherIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a moment. Please wait {0}s....
        /// </summary>
        internal static string NormalRelease_JustAMoment_PleaseWait {
            get {
                return ResourceManager.GetString("NormalRelease_JustAMoment_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New release from {0} is available: v{1} → v{2}.
        /// </summary>
        internal static string NormalRelease_NewReleaseFrom_IsAvailable_v_ {
            get {
                return ResourceManager.GetString("NormalRelease_NewReleaseFrom_IsAvailable_v_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New release is available. Download now!.
        /// </summary>
        internal static string NormalRelease_NewReleaseIsAvailableDownloadNow {
            get {
                return ResourceManager.GetString("NormalRelease_NewReleaseIsAvailableDownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version from {0} is available..
        /// </summary>
        internal static string NormalRelease_NewVersionFrom_IsAvailable {
            get {
                return ResourceManager.GetString("NormalRelease_NewVersionFrom_IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0}.
        /// </summary>
        internal static string NormalRelease_Output_ {
            get {
                return ResourceManager.GetString("NormalRelease_Output_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing... If process is stuck, reopen launcher..
        /// </summary>
        internal static string NormalRelease_Preparing_IfProcessIsStuckReopenLauncher {
            get {
                return ResourceManager.GetString("NormalRelease_Preparing_IfProcessIsStuckReopenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download new update....
        /// </summary>
        internal static string NormalRelease_PreparingToDownloadNewUpdate {
            get {
                return ResourceManager.GetString("NormalRelease_PreparingToDownloadNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong???.
        /// </summary>
        internal static string NormalRelease_SomethingWentWrong {
            get {
                return ResourceManager.GetString("NormalRelease_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string NormalRelease_Starting {
            get {
                return ResourceManager.GetString("NormalRelease_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update size: {0} MB.
        /// </summary>
        internal static string NormalRelease_UpdateSize {
            get {
                return ResourceManager.GetString("NormalRelease_UpdateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating. Please wait....
        /// </summary>
        internal static string NormalRelease_UpdatingPleaseWait {
            get {
                return ResourceManager.GetString("NormalRelease_UpdatingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}s....
        /// </summary>
        internal static string NormalRelease_Waiting_ {
            get {
                return ResourceManager.GetString("NormalRelease_Waiting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found new updates.
        /// </summary>
        internal static string NormalRelease_WeFoundNewUpdates {
            get {
                return ResourceManager.GetString("NormalRelease_WeFoundNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device identifier..
        /// </summary>
        internal static string Os_FailedToRetrieveDeviceIdentifier {
            get {
                return ResourceManager.GetString("Os_FailedToRetrieveDeviceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paimon_gif {
            get {
                object obj = ResourceManager.GetObject("paimon-gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap party_popper {
            get {
                object obj = ResourceManager.GetObject("party-popper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap poland_flag {
            get {
                object obj = ResourceManager.GetObject("poland_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to start the program has been received.
        ///* Debugger is attached: {0}
        ///* CPU Serial Number: {1}
        ///* App dir: {2}
        ///* App data: {3}
        ///* configured.sfn file: {4}
        ///* FPS Unlocker config path: {5}
        ///* Directory for patrons: {6}.
        /// </summary>
        internal static string Program_ARequestToStartTheProgramHasBeenReceived {
            get {
                return ResourceManager.GetString("Program_ARequestToStartTheProgramHasBeenReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to join our Discord server?.
        /// </summary>
        internal static string Program_DoYouWantToJoinOurDiscord {
            get {
                return ResourceManager.GetString("Program_DoYouWantToJoinOurDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send us anonymous log files?.
        /// </summary>
        internal static string Program_DoYouWantToSendUsanonymousLogFiles {
            get {
                return ResourceManager.GetString("Program_DoYouWantToSendUsanonymousLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to send logs to the developer, please send them to me on Discord: Sefinek#2714. API communication is not yet available for the Stella Launcher.
        ///
        ///Do you want to see these files?.
        /// </summary>
        internal static string Program_IfYouWishToSendLogsToTheDeveloperPleaseSendThemToMeOnDiscord {
            get {
                return ResourceManager.GetString("Program_IfYouWishToSendLogsToTheDeveloperPleaseSendThemToMeOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One instance is currently open..
        /// </summary>
        internal static string Program_OneInstanceIsCurrentlyOpen {
            get {
                return ResourceManager.GetString("Program_OneInstanceIsCurrentlyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (MessageBox): Do you want to join our Discord server? Selected: {0}.
        /// </summary>
        internal static string Program_QuestionMessageBox_DoYouWantToJoinOurDiscord_ {
            get {
                return ResourceManager.GetString("Program_QuestionMessageBox_DoYouWantToJoinOurDiscord_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (MessageBox): Do you want to send log files? Selected: {0}.
        /// </summary>
        internal static string Program_QuestionMessageBox_DoYouWantToSendUsanonymousLogFiles_ {
            get {
                return ResourceManager.GetString("Program_QuestionMessageBox_DoYouWantToSendUsanonymousLogFiles_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (MessageBox): Would you share your opinion about Stella Mod on trustpilot.com? I would be very grateful. Selected: {0}.
        /// </summary>
        internal static string Program_QuestionMessageBox_WouldYouShareOpinionAboutStellaMod {
            get {
                return ResourceManager.GetString("Program_QuestionMessageBox_WouldYouShareOpinionAboutStellaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required file &apos;First app launch.exe&apos; was not found. Please reinstall this app or join our Discord server for help..
        /// </summary>
        internal static string Program_RequiredFileFisrtAppLaunchExeWasNotFound_ {
            get {
                return ResourceManager.GetString("Program_RequiredFileFisrtAppLaunchExeWasNotFound_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, one instance is currently open.
        ///
        ///Quit the process with name {0} and try again..
        /// </summary>
        internal static string Program_SorryOneInstanceIsCurrentlyOpen_ {
            get {
                return ResourceManager.GetString("Program_SorryOneInstanceIsCurrentlyOpen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you share your opinion about Stella Mod on trustpilot.com? I would be very grateful..
        /// </summary>
        internal static string Program_WouldYouShareOpinionAboutStellaMod {
            get {
                return ResourceManager.GetString("Program_WouldYouShareOpinionAboutStellaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime name.
        /// </summary>
        internal static string RandomImages_AnimeName {
            get {
                return ResourceManager.GetString("RandomImages_AnimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with the API: {0}
        ///
        ///{1}.
        /// </summary>
        internal static string RandomImages_ErrorWithTheAPI {
            get {
                return ResourceManager.GetString("RandomImages_ErrorWithTheAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating beautiful pictures 😻.
        /// </summary>
        internal static string RandomImages_GeneratingBeautifulPictures {
            get {
                return ResourceManager.GetString("RandomImages_GeneratingBeautifulPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image in default browser.
        /// </summary>
        internal static string RandomImages_OpenImageInDefaultBrowser {
            get {
                return ResourceManager.GetString("RandomImages_OpenImageInDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received data from {0}.
        /// </summary>
        internal static string RandomImages_ReceivedDataFrom {
            get {
                return ResourceManager.GetString("RandomImages_ReceivedDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string RandomImages_Source {
            get {
                return ResourceManager.GetString("RandomImages_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the required file.
        /// </summary>
        internal static string ReShadeIniUpdate_DownloadTheRequiredFile {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_DownloadTheRequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ReShade.ini was not found in your game directory..
        /// </summary>
        internal static string ReShadeIniUpdate_FileReShadeIniWasNotFoundInYourGameDir {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_FileReShadeIniWasNotFoundInYourGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} KB.
        /// </summary>
        internal static string ReShadeIniUpdate_FileSize_KB {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_FileSize_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path was not found on your PC..
        /// </summary>
        internal static string ReShadeIniUpdate_GamePathWasNotFoundOnYourPC {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_GamePathWasNotFoundOnYourPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ReShade config version is available: v{0} → v{1}.
        /// </summary>
        internal static string ReShadeIniUpdate_NewReShadeCfgIsAvailable_v_ {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_NewReShadeCfgIsAvailable_v_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ReShade config version is available. Update is required..
        /// </summary>
        internal static string ReShadeIniUpdate_NewReShadeConfigVersionIsAvailable {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_NewReShadeConfigVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade.ini was not found in: {0}.
        /// </summary>
        internal static string ReShadeIniUpdate_ReShadeIniWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_ReShadeIniWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STELLA.ConfigVersion is null in ReShade.ini..
        /// </summary>
        internal static string ReShadeIniUpdate_StellaConfigVersionIsNullInReShadeIni {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_StellaConfigVersionIsNullInReShadeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of ReShade config was not found..
        /// </summary>
        internal static string ReShadeIniUpdate_TheVersionOfReShadeCfgWasNotFound {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_TheVersionOfReShadeCfgWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ReShade config.
        /// </summary>
        internal static string ReShadeIniUpdate_UpdateReShadeCfg {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_UpdateReShadeCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [i] Update size: {0} KB.
        /// </summary>
        internal static string ReShadeIniUpdate_UpdateSize_KB {
            get {
                return ResourceManager.GetString("ReShadeIniUpdate_UpdateSize_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading resources... {0} MB / {1} MB.
        /// </summary>
        internal static string StellaResources_DownloadingResources {
            get {
                return ResourceManager.GetString("StellaResources_DownloadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update of the resources is available from {0}..
        /// </summary>
        internal static string StellaResources_NewResourcesUpdateIsAvailable {
            get {
                return ResourceManager.GetString("StellaResources_NewResourcesUpdateIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unpacked: {0}.
        /// </summary>
        internal static string StellaResources_SuccessfullyUnpacked {
            get {
                return ResourceManager.GetString("StellaResources_SuccessfullyUnpacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated resources..
        /// </summary>
        internal static string StellaResources_SuccessfullyUpdatedResources {
            get {
                return ResourceManager.GetString("StellaResources_SuccessfullyUpdatedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking files....
        /// </summary>
        internal static string StellaResources_UnpackingFiles {
            get {
                return ResourceManager.GetString("StellaResources_UnpackingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking files... {0} from {1}.
        /// </summary>
        internal static string StellaResources_UnpackingFiles_From_ {
            get {
                return ResourceManager.GetString("StellaResources_UnpackingFiles_From_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking files... {0} from {1}; totalBytes: {2}; totalBytesToExtract: {3};.
        /// </summary>
        internal static string StellaResources_UnpackingFiles_Log {
            get {
                return ResourceManager.GetString("StellaResources_UnpackingFiles_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update size: {0}.
        /// </summary>
        internal static string StellaResources_UpdateSize {
            get {
                return ResourceManager.GetString("StellaResources_UpdateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks :3.
        /// </summary>
        internal static string SupportMe_Thanks {
            get {
                return ResourceManager.GetString("SupportMe_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered telemetry data &apos;{0}&apos; [{1}]..
        /// </summary>
        internal static string Telemetry_DeliveredTelemetryData {
            get {
                return ResourceManager.GetString("Telemetry_DeliveredTelemetryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files was sent to developer..
        /// </summary>
        internal static string Telemetry_LogFilesWasSentToDeveloper {
            get {
                return ResourceManager.GetString("Telemetry_LogFilesWasSentToDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature doesn&apos;t do anything in this release because it hasn&apos;t been created yet!.
        /// </summary>
        internal static string Telemetry_ThisFeatureDoesntDoAnything {
            get {
                return ResourceManager.GetString("Telemetry_ThisFeatureDoesntDoAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing utils 🔧.
        /// </summary>
        internal static string Tools_BrowsingUtils {
            get {
                return ResourceManager.GetString("Tools_BrowsingUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Discord RPC.
        /// </summary>
        internal static string Tools_DisableDiscordRPC {
            get {
                return ResourceManager.GetString("Tools_DisableDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord RPC.
        /// </summary>
        internal static string Tools_EnableDiscordRPC {
            get {
                return ResourceManager.GetString("Tools_EnableDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute music on start.
        /// </summary>
        internal static string Tools_MuteMusicOnStart {
            get {
                return ResourceManager.GetString("Tools_MuteMusicOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade config file was not found in:
        ///{0}.
        /// </summary>
        internal static string Tools_ReShadeConfigFileWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Tools_ReShadeConfigFileWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade log file was not found in:
        ///{0}.
        /// </summary>
        internal static string Tools_ReShadeLogFileWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Tools_ReShadeLogFileWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special background file was not found in &apos;{0}&apos; for Tools window..
        /// </summary>
        internal static string Tools_SpecialBackgroundWasNotFoundIn_ForToolsWindow {
            get {
                return ResourceManager.GetString("Tools_SpecialBackgroundWasNotFoundIn_ForToolsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute music on start.
        /// </summary>
        internal static string Tools_UnmuteMusicOnStart {
            get {
                return ResourceManager.GetString("Tools_UnmuteMusicOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong EnableMusic value in the ini file..
        /// </summary>
        internal static string Tools_WrongEnableMusicValueInTheIniFile {
            get {
                return ResourceManager.GetString("Tools_WrongEnableMusicValueInTheIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected as {0}. Hi and nice to meet you! Check your activity on Discord..
        /// </summary>
        internal static string Tools_YoureConnectedAs__HiAndNiceToMeetYou_CheckYourDiscordActivity {
            get {
                return ResourceManager.GetString("Tools_YoureConnectedAs_.HiAndNiceToMeetYou.CheckYourDiscordActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uk_flag {
            get {
                object obj = ResourceManager.GetObject("uk_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the shortcut.
        ///
        ///{0}.
        /// </summary>
        internal static string Utils_AnErrorOccurredWhileCreatingTheShortcut {
            get {
                return ResourceManager.GetString("Utils_AnErrorOccurredWhileCreatingTheShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop shortcut has been created..
        /// </summary>
        internal static string Utils_DesktopShortcutHasBeenCreated {
            get {
                return ResourceManager.GetString("Utils_DesktopShortcutHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open &apos;{0}&apos; in default browser.
        ///
        ///{1}.
        /// </summary>
        internal static string Utils_FailedToOpen_InDefaultBrowser {
            get {
                return ResourceManager.GetString("Utils_FailedToOpen_InDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exists..
        /// </summary>
        internal static string Utils_File_DoesntNotExists {
            get {
                return ResourceManager.GetString("Utils_File_DoesntNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was found at &apos;{1}&apos;..
        /// </summary>
        internal static string Utils_File_WasFoundAt_ {
            get {
                return ResourceManager.GetString("Utils_File_WasFoundAt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was not found at &apos;{1}&apos;..
        /// </summary>
        internal static string Utils_File_WasNotFoundAt_ {
            get {
                return ResourceManager.GetString("Utils_File_WasNotFoundAt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exists in: {0} [{1}].
        /// </summary>
        internal static string Utils_FileDoesNotExistsIn {
            get {
                return ResourceManager.GetString("Utils_FileDoesNotExistsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exists.
        ///
        ///{0}.
        /// </summary>
        internal static string Utils_FileDoesntNotExists_ {
            get {
                return ResourceManager.GetString("Utils_FileDoesntNotExists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with game path was not found in: {0}.
        /// </summary>
        internal static string Utils_FileWithGamePathWasNotFoundIn {
            get {
                return ResourceManager.GetString("Utils_FileWithGamePathWasNotFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with game path was not found in:
        ///{0}
        ///
        ///Do you want to reconfigure Stella Mod in the configuration window?.
        /// </summary>
        internal static string Utils_FileWithGamePathWasNotFoundIn_DoYouWantToResetAllSMSettings {
            get {
                return ResourceManager.GetString("Utils_FileWithGamePathWasNotFoundIn_DoYouWantToResetAllSMSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with game path does not exists:
        ///{0}
        ///
        ///Do you want to reconfigure Stella Mod in the configuration window?.
        /// </summary>
        internal static string Utils_FolderWithGamePathDoesNotExists_DoYouWantToResetAllSMSettings {
            get {
                return ResourceManager.GetString("Utils_FolderWithGamePathDoesNotExists_DoYouWantToResetAllSMSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Genshin Impact Exe in: {0} [{1}].
        /// </summary>
        internal static string Utils_FoundGiExe {
            get {
                return ResourceManager.GetString("Utils_FoundGiExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Genshin Impact game dir: {0} [{1}].
        /// </summary>
        internal static string Utils_FoundGIgameDir__ {
            get {
                return ResourceManager.GetString("Utils_FoundGIgameDir__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Genshin Impact Launcher in: {0}.
        /// </summary>
        internal static string Utils_FoundGILauncherIn_ {
            get {
                return ResourceManager.GetString("Utils_FoundGILauncherIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found main Genshin Impact dir: {0} [{1}].
        /// </summary>
        internal static string Utils_FoundMainGIDir {
            get {
                return ResourceManager.GetString("Utils_FoundMainGIDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher file does not exists.
        ///
        ///{0}.
        /// </summary>
        internal static string Utils_LauncherFileDoesNotExists {
            get {
                return ResourceManager.GetString("Utils_LauncherFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher file does not exists in: {0} [{1}].
        /// </summary>
        internal static string Utils_LauncherFileDoesNotExistsIn_ {
            get {
                return ResourceManager.GetString("Utils_LauncherFileDoesNotExistsIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened &apos;{0}&apos; in default browser..
        /// </summary>
        internal static string Utils_Opened_InDefaultBrowser {
            get {
                return ResourceManager.GetString("Utils_Opened_InDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the official launcher for Genshin Impact Stella Mod made by Sefinek..
        /// </summary>
        internal static string Utils_RunOfficialLauncherForStellaModMadeBySefinek {
            get {
                return ResourceManager.GetString("Utils_RunOfficialLauncherForStellaModMadeBySefinek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is null or empty..
        /// </summary>
        internal static string Utils_URLIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Utils_URLIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong parameter..
        /// </summary>
        internal static string Utils_WrongParameter {
            get {
                return ResourceManager.GetString("Utils_WrongParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web {
            get {
                object obj = ResourceManager.GetObject("web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Evergreen Standalone Installer..
        /// </summary>
        internal static string WebView2Handler_ChooseEvergreenStandaloneInstaller {
            get {
                return ResourceManager.GetString("WebView2Handler_ChooseEvergreenStandaloneInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Do you want to download this dependency from Microsoft website?.
        /// </summary>
        internal static string WebView2Handler_DoYouWantToDownloadThisDependencyFromMStore {
            get {
                return ResourceManager.GetString("WebView2Handler_DoYouWantToDownloadThisDependencyFromMStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Something went wrong with WebView2..
        /// </summary>
        internal static string WebView2Handler_OhhSorrySomethingWentWrongWithWV2 {
            get {
                return ResourceManager.GetString("WebView2Handler_OhhSorrySomethingWentWrongWithWV2", resourceCulture);
            }
        }
    }
}
