//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellaLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StellaLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_gameplay {
            get {
                object obj = ResourceManager.GetObject("bg_gameplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_links {
            get {
                object obj = ResourceManager.GetObject("bg_links", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_main {
            get {
                object obj = ResourceManager.GetObject("bg_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_support_me {
            get {
                object obj = ResourceManager.GetObject("bg_support-me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_tools {
            get {
                object obj = ResourceManager.GetObject("bg_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat {
            get {
                object obj = ResourceManager.GetObject("cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update ReShade configuration?
        ///
        ///This action will result in the loss of any custom configurations you have made. If you do not have any custom configurations, you may proceed by clicking Yes. However, if you have made changes, please ensure that you have backed up the previous ReShade file in your game files..
        /// </summary>
        internal static string Default_AreYouSureWantToUpdateReShadeConfiguration {
            get {
                return ResourceManager.GetString("Default_AreYouSureWantToUpdateReShadeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background file was not found in &apos;{0}&apos;; ID: {1};.
        /// </summary>
        internal static string Default_BackgroundFileWasNotFoundIn__ID {
            get {
                return ResourceManager.GetString("Default_BackgroundFileWasNotFoundIn_.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached app background in RAM memory &apos;{0}&apos;; ID: {1};.
        /// </summary>
        internal static string Default_CachedAppBackground_ID {
            get {
                return ResourceManager.GetString("Default_CachedAppBackground_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by the user. Are you sure of what you&apos;re doing?.
        /// </summary>
        internal static string Default_CanceledByTheUser_AreYouSureOfWhatYoureDoing {
            get {
                return ResourceManager.GetString("Default_CanceledByTheUser_AreYouSureOfWhatYoureDoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed the launcher background. ID: {0}.
        /// </summary>
        internal static string Default_ChangedTheLauncherBackground_ID {
            get {
                return ResourceManager.GetString("Default_ChangedTheLauncherBackground_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Default_CheckForUpdates {
            get {
                return ResourceManager.GetString("Default_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string Default_CheckingForUpdates {
            get {
                return ResourceManager.GetString("Default_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click „Start game” button to inject ReShade and use FPS Unlock..
        /// </summary>
        internal static string Default_ClickStartGameButtonToInjectReShadeAndUseFPSUnlock {
            get {
                return ResourceManager.GetString("Default_ClickStartGameButtonToInjectReShadeAndUseFPSUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current background: {0}.
        /// </summary>
        internal static string Default_CurrentBackground {
            get {
                return ResourceManager.GetString("Default_CurrentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current background: Default.
        /// </summary>
        internal static string Default_CurrentBackground_Default {
            get {
                return ResourceManager.GetString("Default_CurrentBackground_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted old setup file from temp directory..
        /// </summary>
        internal static string Default_DeletedOldSetupFromTempDirectory {
            get {
                return ResourceManager.GetString("Default_DeletedOldSetupFromTempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted old setup file from temp folder: {0}.
        /// </summary>
        internal static string Default_DeletedOldSetupFromTempFolder {
            get {
                return ResourceManager.GetString("Default_DeletedOldSetupFromTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded ReShade.ini was not found in: {0}.
        /// </summary>
        internal static string Default_DownloadedReShadeIniWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Default_DownloadedReShadeIniWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Default_Downloading {
            get {
                return ResourceManager.GetString("Default_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading config file for FPS Unlocker....
        /// </summary>
        internal static string Default_DownloadingConfigFileForFPSUnlocker {
            get {
                return ResourceManager.GetString("Default_DownloadingConfigFileForFPSUnlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download....
        /// </summary>
        internal static string Default_FailedToDownload {
            get {
                return ResourceManager.GetString("Default_FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download unlocker.config.json..
        /// </summary>
        internal static string Default_FailedToDownloadUnlockerConfigJson {
            get {
                return ResourceManager.GetString("Default_FailedToDownloadUnlockerConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found..
        /// </summary>
        internal static string Default_File_WasNotFound {
            get {
                return ResourceManager.GetString("Default_File_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File download has been canceled by the user..
        /// </summary>
        internal static string Default_FileDownloadHasBeenCanceledByTheUser {
            get {
                return ResourceManager.GetString("Default_FileDownloadHasBeenCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found..
        /// </summary>
        internal static string Default_FileWasNotFound {
            get {
                return ResourceManager.GetString("Default_FileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, you did not give consent for the automatic update of the ReShade file. Please note that older versions of this file may not be compatible with newer versions of Stella Mod. I hope you know what you&apos;re doing..
        /// </summary>
        internal static string Default_ForSomeReasonYouDidNotGiveConsentForTheAutomaticUpdateOfTheReShadeFile {
            get {
                return ResourceManager.GetString("Default_ForSomeReasonYouDidNotGiveConsentForTheAutomaticUpdateOfTheReShadeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game launcher was not found..
        /// </summary>
        internal static string Default_GameLauncherWasNotFound {
            get {
                return ResourceManager.GetString("Default_GameLauncherWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game launcher was not found in: {0}.
        /// </summary>
        internal static string Default_GameLauncherWasNotFoundIn {
            get {
                return ResourceManager.GetString("Default_GameLauncherWasNotFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you are launching the launcher for the first time! Take a moment to review the terms of use on the GitHub Wiki and other guidelines for this modification to avoid any unexpected issues.
        ///
        ///REMEMBER NOT TO SHARE YOUR UID WITH VISIBLE GAME SHADERS WITH ANYONE!.
        /// </summary>
        internal static string Default_ItAppersThatIsYourFirstTimeLaunchingTheLauncher {
            get {
                return ResourceManager.GetString("Default_ItAppersThatIsYourFirstTimeLaunchingTheLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just text. What more do you want?.
        /// </summary>
        internal static string Default_ItsJustText_WhatMoreDoYouWant {
            get {
                return ResourceManager.GetString("Default_ItsJustText_WhatMoreDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeow! Failed to download ReShade.ini. Try again..
        /// </summary>
        internal static string Default_Meeow_FailedToDownloadReShadeIni_TryAgain {
            get {
                return ResourceManager.GetString("Default_Meeow_FailedToDownloadReShadeIni_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any new updates. Your installed version: v{0}.
        /// </summary>
        internal static string Default_NotFoundAnyNewUpdates_YourInstalledVersion_ {
            get {
                return ResourceManager.GetString("Default_NotFoundAnyNewUpdates_YourInstalledVersion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh, something went wrong.
        /// </summary>
        internal static string Default_OhhSomethingWentWrong {
            get {
                return ResourceManager.GetString("Default_OhhSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing sound file: {0}.
        /// </summary>
        internal static string Default_PlayingSoundFile_ {
            get {
                return ResourceManager.GetString("Default_PlayingSoundFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while checking for new updates.
        ///
        ///{0}.
        /// </summary>
        internal static string Default_SomethingWentWrongWhileCheckingForNewUpdates {
            get {
                return ResourceManager.GetString("Default_SomethingWentWrongWhileCheckingForNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Background {0} was not found..
        /// </summary>
        internal static string Default_Sorry_Background_WasNotFound {
            get {
                return ResourceManager.GetString("Default_Sorry.Background_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Default_Success {
            get {
                return ResourceManager.GetString("Default_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded ReShade.ini!.
        /// </summary>
        internal static string Default_SuccessfullyDownloadedReShadeIni {
            get {
                return ResourceManager.GetString("Default_SuccessfullyDownloadedReShadeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded ReShade.ini and saved in: {0}.
        /// </summary>
        internal static string Default_SuccessfullyDownloadedReShadeIniAndSavedIn {
            get {
                return ResourceManager.GetString("Default_SuccessfullyDownloadedReShadeIniAndSavedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved and updated the cached app background with ID {0}..
        /// </summary>
        internal static string Default_SuccessfullyRetrievedAndUpdatedTheCachedAppBackgroundWithID_ {
            get {
                return ResourceManager.GetString("Default_SuccessfullyRetrievedAndUpdatedTheCachedAppBackgroundWithID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application background has been changed to default. ID: {0}.
        /// </summary>
        internal static string Default_TheApplicationBackgroundHasBeenChangedToDefault_ID {
            get {
                return ResourceManager.GetString("Default_TheApplicationBackgroundHasBeenChangedToDefault_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReShade.ini file could not be located in your game files, or it may not be compatible with the current version.
        ///
        ///Would you like to download this file now to prevent future errors and manual configuration? Recommended..
        /// </summary>
        internal static string Default_TheReShadeIniFileCouldNotBeLocatedInYourGameFiles {
            get {
                return ResourceManager.GetString("Default_TheReShadeIniFileCouldNotBeLocatedInYourGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReShade.ini file still does not exist!.
        /// </summary>
        internal static string Default_TheReShadeIniFileStillDoesNotExist {
            get {
                return ResourceManager.GetString("Default_TheReShadeIniFileStillDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound file with music was not found..
        /// </summary>
        internal static string Default_TheSoundFileWithMusicWasNotFound {
            get {
                return ResourceManager.GetString("Default_TheSoundFileWithMusicWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound file with music was not found in the location: &apos;{0}&apos;.
        /// </summary>
        internal static string Default_TheSoundFileWithMusicWasNotFoundInTheLocalization_ {
            get {
                return ResourceManager.GetString("Default_TheSoundFileWithMusicWasNotFoundInTheLocalization_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of ReShade.ini has been cancelled by the user..
        /// </summary>
        internal static string Default_TheUpdateOfReShadIniHasBeenCanceledByTheUser {
            get {
                return ResourceManager.GetString("Default_TheUpdateOfReShadIniHasBeenCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string Default_YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("Default_YouHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_controller {
            get {
                object obj = ResourceManager.GetObject("flaticon_controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_donation {
            get {
                object obj = ResourceManager.GetObject("flaticon_donation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_redo {
            get {
                object obj = ResourceManager.GetObject("flaticon_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flaticon_settings {
            get {
                object obj = ResourceManager.GetObject("flaticon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing the gallery 📷.
        /// </summary>
        internal static string Gallery_BrowsingTheGallery {
            get {
                return ResourceManager.GetString("Gallery_BrowsingTheGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited the gallery 🦊.
        /// </summary>
        internal static string Gallery_ExitedTheGallery {
            get {
                return ResourceManager.GetString("Gallery_ExitedTheGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching gameplay 🎮.
        /// </summary>
        internal static string Gameplay_WatchingGameplay {
            get {
                return ResourceManager.GetString("Gameplay_WatchingGameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_52x52 {
            get {
                object obj = ResourceManager.GetObject("icon_52x52", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_animated {
            get {
                object obj = ResourceManager.GetObject("icons8_animated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_available_updates {
            get {
                object obj = ResourceManager.GetObject("icons8_available-updates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_discord {
            get {
                object obj = ResourceManager.GetObject("icons8_discord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_download_from_the_cloud {
            get {
                object obj = ResourceManager.GetObject("icons8_download-from-the-cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_property {
            get {
                object obj = ResourceManager.GetObject("icons8_edit-property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_gear {
            get {
                object obj = ResourceManager.GetObject("icons8_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_github {
            get {
                object obj = ResourceManager.GetObject("icons8_github", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_info_squared {
            get {
                object obj = ResourceManager.GetObject("icons8_info-squared", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_notepad {
            get {
                object obj = ResourceManager.GetObject("icons8_notepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_recycle_bin {
            get {
                object obj = ResourceManager.GetObject("icons8_recycle-bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shortcut {
            get {
                object obj = ResourceManager.GetObject("icons8_shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_support {
            get {
                object obj = ResourceManager.GetObject("icons8_support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_tools {
            get {
                object obj = ResourceManager.GetObject("icons8_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_web {
            get {
                object obj = ResourceManager.GetObject("icons8_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_youtube {
            get {
                object obj = ResourceManager.GetObject("icons8_youtube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the window with links 🌍.
        /// </summary>
        internal static string Links_DRPC_OnTheWindowWithLinks {
            get {
                return ResourceManager.GetString("Links_DRPC_OnTheWindowWithLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked No in form &apos;{0}&apos;..
        /// </summary>
        internal static string Main_ClickedNoInForm_ {
            get {
                return ResourceManager.GetString("Main_ClickedNoInForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked Yes in form &apos;{0}&apos;..
        /// </summary>
        internal static string Main_ClickedYesInForm_ {
            get {
                return ResourceManager.GetString("Main_ClickedYesInForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed..
        /// </summary>
        internal static string Main_Closed {
            get {
                return ResourceManager.GetString("Main_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed form {0}..
        /// </summary>
        internal static string Main_ClosedForm_ {
            get {
                return ResourceManager.GetString("Main_ClosedForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing form {0}....
        /// </summary>
        internal static string Main_ClosingForm_ {
            get {
                return ResourceManager.GetString("Main_ClosingForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded form {0}..
        /// </summary>
        internal static string Main_LoadedForm_ {
            get {
                return ResourceManager.GetString("Main_LoadedForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_release {
            get {
                object obj = ResourceManager.GetObject("new-release", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paimon_gif {
            get {
                object obj = ResourceManager.GetObject("paimon-gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap party_popper {
            get {
                object obj = ResourceManager.GetObject("party-popper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap poland_flag {
            get {
                object obj = ResourceManager.GetObject("poland_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to start the program has been received.
        ///* Debugger is attached: {0}
        ///* CPU Serial Number: {1}
        ///* App dir: {2}
        ///* App data: {3}
        ///* configured.sfn file: {4}
        ///* FPS Unlocker config path: {5}
        ///* Directory for patrons: {6}.
        /// </summary>
        internal static string Program_ARequestToStartTheProgramHasBeenReceived {
            get {
                return ResourceManager.GetString("Program_ARequestToStartTheProgramHasBeenReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to join our Discord server?.
        /// </summary>
        internal static string Program_DoYouWantToJoinOurDiscord {
            get {
                return ResourceManager.GetString("Program_DoYouWantToJoinOurDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send us anonymous log files?.
        /// </summary>
        internal static string Program_DoYouWantToSendUsanonymousLogFiles {
            get {
                return ResourceManager.GetString("Program_DoYouWantToSendUsanonymousLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to send logs to the developer, please send them to me on Discord: Sefinek#2714. API communication is not yet available for the Stella Launcher.
        ///
        ///Do you want to see these files?.
        /// </summary>
        internal static string Program_IfYouWishToSendLogsToTheDeveloperPleaseSendThemToMeOnDiscord {
            get {
                return ResourceManager.GetString("Program_IfYouWishToSendLogsToTheDeveloperPleaseSendThemToMeOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One instance is currently open..
        /// </summary>
        internal static string Program_OneInstanceIsCurrentlyOpen {
            get {
                return ResourceManager.GetString("Program_OneInstanceIsCurrentlyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (MessageBox): Do you want to send log files? Selected: {0}.
        /// </summary>
        internal static string Program_QuestionDoYouWantToSendUsanonymousLogFiles_ {
            get {
                return ResourceManager.GetString("Program_QuestionDoYouWantToSendUsanonymousLogFiles_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (MessageBox): Do you want to join our Discord server? Selected: {0}.
        /// </summary>
        internal static string Program_QuestionMessageBox_DoYouWantToJoinOurDiscord_ {
            get {
                return ResourceManager.GetString("Program_QuestionMessageBox_DoYouWantToJoinOurDiscord_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required file &apos;First app launch.exe&apos; was not found. Please reinstall this app or join our Discord server for help..
        /// </summary>
        internal static string Program_RequiredFileFisrtAppLaunchExeWasNotFound_ {
            get {
                return ResourceManager.GetString("Program_RequiredFileFisrtAppLaunchExeWasNotFound_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, one instance is currently open.
        ///
        ///Quit the process with name {0} and try again..
        /// </summary>
        internal static string Program_SorryOneInstanceIsCurrentlyOpen_ {
            get {
                return ResourceManager.GetString("Program_SorryOneInstanceIsCurrentlyOpen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime name.
        /// </summary>
        internal static string RandomImages_AnimeName {
            get {
                return ResourceManager.GetString("RandomImages_AnimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with the API: {0}
        ///
        ///{1}.
        /// </summary>
        internal static string RandomImages_ErrorWithTheAPI {
            get {
                return ResourceManager.GetString("RandomImages_ErrorWithTheAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating beautiful pictures 😻.
        /// </summary>
        internal static string RandomImages_GeneratingBeautifulPictures {
            get {
                return ResourceManager.GetString("RandomImages_GeneratingBeautifulPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image in default browser.
        /// </summary>
        internal static string RandomImages_OpenImageInDefaultBrowser {
            get {
                return ResourceManager.GetString("RandomImages_OpenImageInDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received data from {0}.
        /// </summary>
        internal static string RandomImages_ReceivedDataFrom {
            get {
                return ResourceManager.GetString("RandomImages_ReceivedDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string RandomImages_Source {
            get {
                return ResourceManager.GetString("RandomImages_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks :3.
        /// </summary>
        internal static string SupportMe_Thanks {
            get {
                return ResourceManager.GetString("SupportMe_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing utils 🔧.
        /// </summary>
        internal static string Tools_BrowsingUtils {
            get {
                return ResourceManager.GetString("Tools_BrowsingUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Discord RPC.
        /// </summary>
        internal static string Tools_DisableDiscordRPC {
            get {
                return ResourceManager.GetString("Tools_DisableDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord RPC.
        /// </summary>
        internal static string Tools_EnableDiscordRPC {
            get {
                return ResourceManager.GetString("Tools_EnableDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute music on start.
        /// </summary>
        internal static string Tools_MuteMusicOnStart {
            get {
                return ResourceManager.GetString("Tools_MuteMusicOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade config file was not found in:
        ///{0}.
        /// </summary>
        internal static string Tools_ReShadeConfigFileWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Tools_ReShadeConfigFileWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade log file was not found in:
        ///{0}.
        /// </summary>
        internal static string Tools_ReShadeLogFileWasNotFoundIn_ {
            get {
                return ResourceManager.GetString("Tools_ReShadeLogFileWasNotFoundIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special background file was not found in &apos;{0}&apos; for Tools window..
        /// </summary>
        internal static string Tools_SpecialBackgroundWasNotFoundIn_ForToolsWindow {
            get {
                return ResourceManager.GetString("Tools_SpecialBackgroundWasNotFoundIn_ForToolsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute music on start.
        /// </summary>
        internal static string Tools_UnmuteMusicOnStart {
            get {
                return ResourceManager.GetString("Tools_UnmuteMusicOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong EnableMusic value in the ini file..
        /// </summary>
        internal static string Tools_WrongEnableMusicValueInTheIniFile {
            get {
                return ResourceManager.GetString("Tools_WrongEnableMusicValueInTheIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected as {0}. Hi and nice to meet you! Check your activity on Discord..
        /// </summary>
        internal static string Tools_YoureConnectedAs__HiAndNiceToMeetYou_CheckYourDiscordActivity {
            get {
                return ResourceManager.GetString("Tools_YoureConnectedAs_.HiAndNiceToMeetYou.CheckYourDiscordActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uk_flag {
            get {
                object obj = ResourceManager.GetObject("uk_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web {
            get {
                object obj = ResourceManager.GetObject("web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
